name: 'Docker Push to ECR'
description: 'Push Docker image to ECR repository'

inputs:
  aws_account_id:
    description: 'AWS Account ID'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  iam_deployer_role_name:
    description: 'IAM role name for deployment'
    required: true
  ecr_repository_name:
    description: 'ECR repository name'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
  push_latest:
    description: 'Whether to also tag and push as latest'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.iam_deployer_role_name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Docker image
      shell: bash
      run: |
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY=${{ inputs.ecr_repository_name }}
        IMAGE_TAG=${{ inputs.image_tag }}
        IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Push image
        docker push $IMAGE_URI
        echo "Pushed: $IMAGE_URI"
        
        # Also tag and push as latest if requested
        if [ "${{ inputs.push_latest }}" = "true" ]; then
          docker tag $IMAGE_URI $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "Also pushed as latest"
        fi 