name: Production Environment
run-name: Deploy to Production - ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      skip_terraform:
        description: 'Skip Terraform deployment'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Manual approval gate for production
  approve-deployment:
    name: 🔒 Approve Production Deployment
    runs-on: ubuntu-latest
    environment: 
      name: production-approval
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Approval Gate
        run: |
          echo "✅ Production deployment approved"
          echo "Deploying to production environment..."

  deploy-to-prod:
    name: 🚀 Deploy to Production
    needs: approve-deployment
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      environment: prod
      aws_region: us-east-1
      terraform_version: '1.5.0'
      runner_labels: ubuntu-latest
      skip_terraform: ${{ inputs.skip_terraform || false }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      iam_deployer_role_name: ${{ secrets.IAM_DEPLOYER_ROLE_NAME }}
