name: 'Terraform Validation'
description: 'Validate Terraform configuration with fmt, validate, and tfsec'

inputs:
  working_directory:
    description: 'Directory containing Terraform code'
    required: false
    default: './terraform'
  terraform_version:
    description: 'Terraform version to use'
    required: false
    default: '1.5.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Format Check
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "::group::Terraform Format Check"
        terraform fmt -check -recursive || {
          echo "::error::Terraform files are not properly formatted. Run 'terraform fmt -recursive' locally."
          exit 1
        }
        echo "::endgroup::"

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "::group::Terraform Init"
        terraform init -backend=false
        echo "::endgroup::"

    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "::group::Terraform Validate"
        terraform validate
        echo "::endgroup::"

    - name: Run tfsec (Security Scanning)
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ inputs.working_directory }}
        soft_fail: true
        format: default
        additional_args: --minimum-severity MEDIUM
